### ISSUE TITLE
AttributeError: 'AutoBufferedPaintDC' object has no attribute 'LogicalToDevice'

### ISSUE THREAD

**Issue by richardklingler** [Najsztub/jtagGUI#1]
Just installed jtagGUI on my Debian 11.1 box and when launching I see in the console loads of error messages:

`Traceback (most recent call last):
  File "/home/klingler/develop/jtagGUI/Panels/RightPanel.py", line 109, in OnPaint
    self.logical_origin = dc.LogicalToDevice(0,0)
AttributeError: 'AutoBufferedPaintDC' object has no attribute 'LogicalToDevice'
Traceback (most recent call last):
  File "/home/klingler/develop/jtagGUI/Panels/RightPanel.py", line 109, in OnPaint
    self.logical_origin = dc.LogicalToDevice(0,0)
AttributeError: 'AutoBufferedPaintDC' object has no attribute 'LogicalToDevice'
`
Detecting an Altera EP4CE15F23 device works....

Setting a pin state doesn't do antything...or at least it isn't docuemnted how to achieve this (o;
Only when clicking "Shift DR" I get:

`urjtag.error: out of bounds: register length 1 mismatch: 1080`

**Comment by richardklingler** [comment]
Seems distribution problems as Debian 11.1 doesn't ship a recent wx library as LogicalToDevcie is missing...

This works so far:

`self.logical_origin = wx.Point(dc.LogicalToDeviceX(0), dc.LogicalToDeviceY(0))`

Still not able to set pin states...

**Comment by richardklingler** [comment]
Gonna do an own issue for the urjtag register length mismatch...

**Comment by Najsztub** [comment]
Hi! 

Thanks for pointing out this issue. I was able to confirm this with a Manjaro install with wxPython 4.0.7 installed from the AUR. I wasn't able to reproduce this with wxPython 4.1.1, but I included your fix.

Thanks again.
