### ISSUE TITLE
Window resize causes columns of left panel to disappear

### ISSUE THREAD

**Issue by richardklingler** [Najsztub/jtagGUI#3]
This is the screen after starting up (I changed default size as 640x480 is too small), only the Properties columns is visible:

![jtag_1](https://user-images.githubusercontent.com/11256235/143030459-afa2ee6e-db82-4fae-9fa2-1e6f82dfaa61.png)

Now when I resize it to make it smaller:

![jtag_2](https://user-images.githubusercontent.com/11256235/143030537-aa0b60a6-65b5-4eec-bae6-1e1b89a02809.png)

and smaller:

![jtag_3](https://user-images.githubusercontent.com/11256235/143030575-1b573726-eb6b-42e7-9930-2964daa0e64a.png)

and then make it larger:

![jtag_4](https://user-images.githubusercontent.com/11256235/143030601-869075da-487f-4b3f-9e4b-e640324abf78.png)

and resize it again:

![jtag_5](https://user-images.githubusercontent.com/11256235/143030628-8e91e693-9aec-4cb2-8ad9-f900a9dcd9fc.png)

So now some columns of the left panel are missing and can't be readjusted to make it visible again

**Comment by Najsztub** [comment]
Hey,

For the first screen. Is this the default behaviour or did you change the code? When I try to run the app both under Win10 and Manjaro Linux I do not see this behaviour. 

Just to be sure I increased the default window size to 800x600 px.

I also changed the default left panel size to auto.

I cannot find a simple solution for now that would block the first column in the upper left panel form reaching 0 width.

**Comment by richardklingler** [comment]
Did a short screencast.....same thing happens when I leave the main window size as it was....

https://www.youtube.com/watch?v=7noNtqAD8Nk

**Comment by Najsztub** [comment]
OK, now I get it. This is strange. Unfortunately I can't replicate this behaviour on my systems. I tried to set the first column width directly during initialization. Before that I was using `wx.COL_WIDTH_AUTOSIZE` which I suspect might have caused problems. Could you tell me if the newest commit fixed this shrinking column issue?

**Comment by Najsztub** [comment]
I've installed Debian and now I can confirm this behaviour with python3-wxgtk4.0, wxPython ver. 4.0.7.

I still cannot solve this issue.

**Comment by Najsztub** [comment]
After trying to work out Forms parameters, I'm afraid that this is a general wxPython bug that has already been posted here: wxWidgets/Phoenix#676. 

There's not much I can help here, but suggest upgrading to newest version of wxPython.
