### ISSUE TITLE
Cannot find urjtag package

### ISSUE THREAD

**Issue by hansfbaier** [Najsztub/jtagGUI#6]
```
$ pip3 install urjtag
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement urjtag (from versions: none)
ERROR: No matching distribution found for urjtag
```

**Comment by hansfbaier** [comment]
Where do I get the urjtag package from?

**Comment by Najsztub** [comment]
Hi, 

you need compile UrJTAG [from source](https://sourceforge.net/projects/urjtag/) and include Python bindings during compilation. More info can be found [here](https://github.com/shuckc/urjtag/blob/master/urjtag/doc/urjtag-python.txt).

Best,
MN
